<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $page->title }} - Our Store</title>
    <!-- Basic Bootstrap for structure if the builder didn't inject any -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    
    <style>
        /* Inject the custom CSS generated by GrapesJS */
        {!! $page->css !!}
    </style>
</head>
<body>
    <!-- Inject the raw HTML layout built via drag-and-drop -->
    {!! $page->html !!}
</body>
</html>
